### ISSUE TITLE
Community Charts Suggestion: Flaresolverr

### ISSUE THREAD

**Issue by imjustleaving** [truenas/charts#1381]
would be great to have this for the arr stack.

[https://github.com/FlareSolverr/FlareSolverr](https://github.com/FlareSolverr/FlareSolverr)

**Comment by Gujal00** [comment]
+1

**Comment by xchwarze** [comment]
@imjustleaving I understand that the correct way to implement it would be with "Custom App"
https://www.truenas.com/docs/scale/24.04/scaletutorials/apps/usingcustomapp/

I used this Docker Compose as a guide to setup it:
```
version: "2.1"
services:
 flaresolverr:
   image: ghcr.io/flaresolverr/flaresolverr:latest
   container_name: flaresolverr
   environment:
     - LOG_LEVEL=info
     - LOG_HTML=false
     - CAPTCHA_SOLVER=none
     - TZ=America/New_York
   ports:
     - 8191:8191
   restart: unless-stopped
```
