### ISSUE TITLE
Home Assistant - Add host device support

### ISSUE THREAD

**Issue by KKWait** [truenas/charts#1478]
Hi,

I'm using Home Assistant  (1.0.105 current build) app through TrueNas Scale, but it lacks a feature to provide host device access, such as usb device (rf433, z-wave, ...) to be really usefull. 
I tried to edit the pre-install-job.yaml file located in /mnt/app-pool/ix-applications/catalogs/github_com_truenas_charts_git_master/charts/home-assistant/1.0.105/templates to append :
      devices:
        - /dev/ttyUSB0:/dev/ttyACM0
        - /dev/ttyUSB1:/dev/ttyACM1

But it doesn't seems to be taken into consideration

Is there any chance to see a future version implementing the device integration ?
Or is there any tricky workaround ? (I know it could be ran into a VM that provide direct access to host devices, but ideally, Id like to avoid that, since I just migrated from ESXi with Trenas VM to bare metal TrueNas ... and VMs are not the future contrary to containers)

Thanks !

**Comment by tapayne88** [comment]
I was hoping to do the same thing. I ended up getting something working by mapping the drive using the 'Extra Host Path Volumes' and editing the deployment's security context.

<img width="768" alt="Screenshot 2023-10-19 at 16 58 08" src="https://github.com/truenas/charts/assets/991180/e4a3e1ea-12ae-4a58-974b-4812678be931">

To edit the deployment run the following from a truenas shell (assuming you used the default naming)
```
k3s kubectl --namespace ix-home-assistant edit deployment home-assistant
```

Adding the following under the home-assistant container (not the postgres) _might_ get it working 🤞 
```yaml
    spec:
      containers:
        ...
        image: homeassistant/home-assistant:2023.10.2              # <- find this and add the below
        securityContext:
          privileged: true
```

Hope this helps! I'm happy to raise a PR @stavros-k
