### ISSUE TITLE
Error in storage declaration prevents upgrading firefly-iii

### ISSUE THREAD

**Issue by danielegobbetti** [truenas/charts#1679]
Hello,

allow me to start saying that I have no knowledge of k3s and helm charts, but was affected by an issue when trying to upgrade firefly-iii. The upgrade would fail stating that ``pgData`` and ``pgBackup`` hostPath were not existing, this despite the fact that I configured them as ``ixVolume`` and not ``hostPath``.

Noticing that only two of three paths were giving the error, I noticed that in this file:

https://github.com/truenas/charts/blob/8efa7c3f96904543f887d3deebd0359265ff5f62/community/firefly-iii/1.0.7/ix_values.yaml#L27

the ``uploads`` storage is declared of type ``ixVolume`` and has a ``datasetName`` defined, whereas the ``pgData`` and ``pgBackup`` has type ``ixVolume`` but a ``hostPath`` defined.

I changed the two latter definition to have a ``datasetName`` instead of ``hostPath`` and could finally upgrade.

Please note that I am not creating a PR because I have no idea if what I did is correct or wrong. Anyway, I changed from this:

```
fireflyStorage:
  uploads:
    type: ixVolume
    datasetName: uploads
  pgData:
    type: ixVolume
    hostPath: pgData
  pgBackup:
    type: ixVolume
    hostPath: pgBackup
```

to this:

```
fireflyStorage:
  uploads:
    type: ixVolume
    datasetName: uploads
  pgData:
    type: ixVolume
    datasetName: pgData
  pgBackup:
    type: ixVolume
    datasetName: pgBackup
```

then opened and saved configuration without any change and could finally upgrade firefly-iii.
