### ISSUE TITLE
Apps lost permissions after update to 24.10

### ISSUE THREAD

**Issue by Karmalakas** [truenas/charts#2927]
So I noticed some apps no longer properly deal with permissions. All were running fine on 24.04

- Deluge can no longer access downloaded files
- Homepage dashboard can no longer access mounted config dataset
 
 If I install Homepage via new Yaml option, then it works as expected (although I don't know how to define the web portal, so the button would appear in TrueNAS UI):
 ```
 services:
  homepage:
    container_name: homepage-ca
    environment:
      PGID: 568
      PUID: 568
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - '30054:3000'
    volumes:
      - /mnt/Apps/Data/homepage:/app/config
 ```
The charts version is running with `1000:1000`, but neither user nor group with ID `1000` exists, so I guess that's the problem 😕 

I guess time will tell if there are more apps that are broken after the update. So far others open, but Deluge opens too. Only after a bit of digging I found it lost permissions to the files it created itself...
