### ISSUE TITLE
How to update parameters UI while developing a chart

### ISSUE THREAD

**Issue by docwhite** [truenas/charts#45]
Hello,

I am experimenting by bringing the `test/minio/1.2.1` into `charts/minio/1.2.1` and changing or adding the `questions.yaml` so that I can see how to include extra fields on the UI that shows when you want to install an app from the catalog.

I have no success, I am working on my own fork, and I install it by:

```
midclt call catalog.create '{"label": "docwhite", "repository": "https://github.com/docwhite/charts", "branch": "temp"}'
```

And even after changing some parameters they won't reflect on the UI.

I tried issuing `midclt call catalog.validate` and `midclt call catalog sync` and still doesn't show.

Is there any refresh command that would regenerate those parameter interfaces?

**Comment by sonicaj** [comment]
@docwhite can you please confirm where you are making edits after adding the catalog ? Are you making the edit and then pushing to github and then using `catalog.sync` or are you editing directly under `/mnt/POOLNAMEHERE/ix-applications/catalogs/repo_path/` and then seeing if the changes are reflected ?

**Comment by docwhite** [comment]
I tried doing both.

I first moved the minio from test to charts and just after that I added a test parameter, expecting it to see it reflected:

https://github.com/docwhite/charts/compare/master...docwhite:temp#diff-702ebe9d6219bc28256e1cf99980c0a5d3ad1953df9a496e485552ddfa387c00

Sorry for the absurd variable name >.< I do it that way so I never push it to master, since it's easy to spot.

```
       min_length: 5
      max_length: 20

  - variable: potato
    label: "Potato"
    group: "Minio Configuration"
    description: "Enter the Potato"
    schema:
      type: string
      private: true
      required: true
      min_length: 5
      max_length: 20

  - variable: secretKey
    label: "Secret Key"
    group: "Minio Configuration"
```
